sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Nu1z60JCQxaCUc4QkmLO/85z9F0YMnOGgCgnANrTmcSZFZ8xwJUTGu9MVVoBfr79qT+LZd1+hphIo7o0N22BxHW67J8yZZAMMQ4io0nU+/WOxohHRos01nekKetWWeI4Y8F3pcYvihf+sPdQ80pZV0IJv775/Po2w9DLwmcvhBApm5JEAKalEhhbB2a9i7rDB/1TkR4Dx+sDWIihc+xVO6zQ/qwfJ1CpFWjd4RayL3Hnvsgpzhnu/Y8HvF9zxH3PtevPbbmeHVeoQwhc9g8WIXKgIR6rKhtEcDw/3+XMxxBLTxm8V5pMClXmyNOUOy4s7HixPjnJiyFG2PVN7W4NsKoMAwzYO4ScAL8MNqAB48UZcstMQ6WWwV9nb010xkGUmD3MiKF6a0e69NzSypfBgqURTxN1wzro5Qnt/wPR5qu7q4mqKT70x+eJrsE8WDxKcn5mxBcwx84AeHn2pqWxsEh9zOlHw5XWSXTJgxG63yErgWx6B7E2HWqW+QEoF5rMTxuimVczkrwxQjXcNe+y8ckhxbKShw+kVjigOZoEBCi9oUd4aXPCZzYq1WRqjC0vsigbopRc8/bPgGPok/TFKE0um84dmjCABgal55w3TFjkuE5PoZS6NBACLWBqaUPv73rrhcW198fKSOI/Z41T7jvzJ3r0MzmPEqmHiz/Vupk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Pit-Prop-Syndicate_2013
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy